version: "3.8"

services:
  httpd2:
    container_name: httpd2
    image: httpd:latest
    ports:
      - protocol: tcp
        published: 80 
        target: 80
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 50M
        limits:
          cpus: "0.5"
          memory: 100M
    