version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: adrianadhari
      MONGO_INITDB_ROOT_PASSWORD: pekacu663
      MONGO_INITDB_DATABASE: admin
    networks:
      - mongo_network

  mongodb-express:
    image: mongo-express:latest
    container_name: mongodb-express
    restart: always
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: anjay
      ME_CONFIG_BASICAUTH_PASSWORD: anjay
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: adrianadhari
      ME_CONFIG_MONGODB_ADMINPASSWORD: pekacu663
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongo_network
    depends_on:
      - mongodb

networks:
  mongo_network:
    name: mongo_network
    driver: bridge
